### ISSUE TITLE
Fix categories expander

### ISSUE THREAD

**Issue by AsciiWolf** [ubuntu/snap-store#67]
The categories expander button is [constantly broken](https://gitlab.gnome.org/GNOME/gnome-software/issues/607) and so it was [removed](https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/246) in upstream. However, there was a workaround [suggested](https://gitlab.gnome.org/GNOME/gnome-software/issues/607#note_545721) to fix the expander. It's untested, but it could work. Consider fixing the expander button using this workaround.

**Comment by robert-ancell** [comment]
Are you referring to the GNOME Software based store distributed as the 'snap-store' snap? If so, this bug should be filed in https://bugs.launchpad.net/ubuntu/+source/gnome-software. Thanks!

**Comment by AsciiWolf** [comment]
Isn't this a Git repo for the "GNOME Software based store"? And I see that the other issues [reported here](https://github.com/ubuntu/snap-store/issues) are also related to the "GNOME Software based store". I don't understand the point of this. Anyway, this was just a friendly suggestion how to fix the constantly broken button. :-)

**Comment by robert-ancell** [comment]
Some issues here refer to the GNOME Software based store, but that is developer here:
https://gitlab.gnome.org/Community/Ubuntu/gnome-software/tree/snap-store

**Comment by AsciiWolf** [comment]
Ah, fair enough. I have reported it [here](https://bugs.launchpad.net/ubuntu/+source/gnome-software/+bug/1835969).
